version: '3'
services:

  nginx:
    image: nginx:latest
    container_name: 'web'
    volumes:
        - ./src:/var/www/test
        - ./etc/config:/var/configs
    ports:
        - "80:80"
    command: /bin/sh -c "cp /var/configs/nginx.conf /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always

  php:
    image: php:7.4-fpm
    container_name: 'php'
    volumes:
      - ./src:/var/www/test
    ports:
      - "9000:9000"
    restart: always
